### ISSUE TITLE
Can't install on Yosemite

### ISSUE THREAD

**Issue by wndxlori** [hybridgroup/kidsrubyinstaller-osx#11]
Same error message as https://github.com/hybridgroup/kidsrubyinstaller-osx/issues/9, so I assume that it's a similar problem?

**Comment by YJH1987** [comment]
cannot install on Yosemite. any suggestion?

**Comment by wndxlori** [comment]
I forked, fixed some file paths, and now I am at:

```
$ ./build_installer.sh GLC
Copied KidsRuby.app/Contents/MacOS/KidsRuby
/Users/lori/Dropbox/Projects/llcode/kidsrubyinstaller-osx/build/KidsRuby.app
a KidsRuby.app
a KidsRuby.app/Contents
a KidsRuby.app/Icon\r
a KidsRuby.app/Contents/MacOS
a KidsRuby.app/Contents/MacOS/KidsRuby
Warning: '/Users/lori/Dropbox/Projects/llcode/kidsrubyinstaller-osx/kidsruby.icns' not identified as an Apple .icns file
Error: No file exists at path '/Users/lori/Dropbox/Projects/llcode/kidsrubyinstaller-osx/resources/qtbindings-4.7.3-universal-darwin-10.gem'
hdiutil: create failed - No such file or directory
mv: rename KidsRubyInstaller.app.dmg to kidsrubyinstaller-GLC.dmg: No such file or directory
```

Not really sure where that qtbindings gem is supposed to come from.  I downloaded 

http://github.com/ryanmelt/qtbindings

And symlinked it under /Developer

Also downloaded

https://github.com/hybridgroup/ruby-serialport

And symlinked that under /Developer/serialport

More details here:

https://gist.github.com/wndxlori/ed8b82d8e6838c1884ae

**Comment by jjnevis** [comment]
I've just come up against this issue (Yosemite 10.10.3). My 8 year old has just expressed an interest in programming (shock horror!) - I talked her through changing a Rubymotion app to put her name on the screen, so I was looking into gentle introductions to programming. Any other suggestions of kids programming tools to fire her imagination?

**Comment by hunterboerner** [comment]
http://www.codecademy.com/
http://www.codecademy.com/tracks/ruby

**Comment by jjnevis** [comment]
Aye, but is that cool for an 8 year old? I'm just about to download Hackety-Hack to check out...

(sorry if I've just hijacked this issue for off-topic purposes)

**Comment by hunterboerner** [comment]
Dunno. @deadprogram may be of more help.

**Comment by jjnevis** [comment]
@hunterboerner thanks for you input, (PS your avatar reminds me of one of the characters from "Penguins of Madagascar", which I've recently seen and is brilliant! - one of the upsides of having 3 challenging young children)

**Comment by wndxlori** [comment]
Here's the repo with slides/exercises/answers that I used to teach a Girls Learning Code workshop for 8-13 yr olds.

https://github.com/wndxlori/glc-ruby

**Comment by jjnevis** [comment]
Thanks @wndxlori. I'll hand this thread back to it's original purpose now: "Can't install on Yosemite"
