### ISSUE TITLE
Compatibility with Mountain Lion

### ISSUE THREAD

**Issue by deadprogram** [hybridgroup/kidsrubyinstaller-osx#9]
Seems there is some problem with KidsRuby on Mountain Lion. We need some details...

**Comment by tgizzle** [comment]
Installer says "Sorry KidsRuby is not currently supported on your operating system."

**Comment by tgizzle** [comment]
Could it be this (in installer.sh):

check_osx_version() {
  TIGER=4
  LEOPARD=5
  SNOW_LEOPARD=6
  LION=7
  osx_version=$(sw_vers -productVersion | awk 'BEGIN {FS="."}{print $2}')
  if [ $osx_version -eq $LEOPARD -o $osx_version -eq $SNOW_LEOPARD -o $osx_version -eq $LION ]; then
    echo $KIDSRUBY_START_INSTALL
  else
    echo $KIDSRUBY_ERROR_NOT_SUPPORTED
    exit
  fi
}

**Comment by tgizzle** [comment]
Confirmed changing to this allowed install:

# determine OSX version

TIGER=4
LEOPARD=5
SNOW_LEOPARD=6
LION=7
MOUNTAIN_LION=8
osx_version=$(sw_vers -productVersion | awk 'BEGIN {FS="."}{print $2}')
if [ $osx_version -eq $LEOPARD -o $osx_version -eq $SNOW_LEOPARD -o $osx_version -eq $LION -o $osx_version -eq $MOUNTAIN_LION ]; then
    echo "Starting KidsRuby install..."
else
    echo "Sorry, KidsRuby is not currently supported on your operating system."
    exit
fi

**Comment by deadprogram** [comment]
Thanks, I will try this out this weekend. It is appreciated!

On Thu, Aug 9, 2012 at 6:04 PM, tgizzle notifications@github.com wrote:

> Confirmed changing to this allowed install:
> determine OSX version
> 
> TIGER=4
> LEOPARD=5
> SNOW_LEOPARD=6
> LION=7
> MOUNTAIN_LION=8
> 
> osx_version=$(sw_vers -productVersion | awk 'BEGIN {FS="."}{print $2}')
> if [ $osx_version -eq $LEOPARD -o $osx_version -eq $SNOW_LEOPARD -o
> $osx_version -eq $LION -o $osx_version -eq $MOUNTAIN_LION ]; then
> echo "Starting KidsRuby install..."
> else
> echo "Sorry, KidsRuby is not currently supported on your operating system."
> exit
> fi
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/hybridgroup/kidsrubyinstaller-osx/issues/9#issuecomment-7631652.

## 

Ron Evans
The Hybrid Group
http://hybridgroup.com
p. 310-916-9924
m. 310-597-1013

**Comment by deadprogram** [comment]
Fixed by commit https://github.com/hybridgroup/kidsrubyinstaller-osx/commit/5617831f7e5d251a53ecbf25206313e653519ba2
